### PR TITLE
Added --latest-commit-hash option

### PR DESCRIPTION
**Pull request by Amaljith-K**
- Same as #1

### CODE REVIEW

**Comment by Amaljith-K** [comment]
@AbhayVAshokan _a With the introduction of new changes, several tests are failing. Can you correct them to ensure the sanity of the repo?
It will also help us figuring out bugs before testing in production

**Comment by AbhayVAshokan** [comment]
@Amaljith-K _a please have a look; https://vimeo.com/751226203/d10f58e85c

I am not familiar with PHP and am taking too much time writing something in it. Can you please take it up?

**Comment by Amaljith-K** [comment]
I've enabled issues, projects & wiki for this repo.
I'll take up the rest of the works.

**Comment by Amaljith-K** [comment]
I could see a lot of redundant changes here. I'm closing this. I'll reopen a new PR

**Pull request closed without merging**
